### PR TITLE
Fixes for the python module

### LINKED ISSUE #125: Importing Python bindings gives "TypeError: _argtypes_ must be a sequence of types"
This happens on both Python 2.7.18 and 3.8.3, Arch Linux, libproxy 0.4.15 (commit 454a499)

EDIT: last check with Python 3.9.0, libproxy 0.4.16

To reproduce:
```
$ python -m libproxy
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.8/site-packages/libproxy.py", line 48, in <module>
    _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p)
TypeError: _argtypes_ must be a sequence of types
```
or interactively:
```
$ python
Python 3.8.3 (default, May 17 2020, 18:15:42) 
[GCC 10.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import libproxy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.8/site-packages/libproxy.py", line 48, in <module>
    _libproxy.px_proxy_factory_free_proxies.argtypes = ctypes.POINTER(ctypes.c_void_p)
TypeError: _argtypes_ must be a sequence of types
>>>
```

### PR DESCRIPTION
**Pull request by bigon**
Hello,

Please find a here a pull request that should fix #125 

Please review it, my knowledge of ctypes in python is almost null

### CODE REVIEW

**Comment by DimStar77** [comment]
```
>>> import libproxy
>>> URL = "http://www.google.com"
>>> pf = libproxy.ProxyFactory()
>>> for proxy in pf.getProxies(URL):
...   print("Trying to load URL %s via proxy %s" % (URL, proxy))
... 
Segmentation fault (core dumped)
```

with #147, the same code works

**Comment by bigon** [comment]
That's weird, with python3.9 here on my debian, it works

**Comment by DimStar77** [comment]
Let's go with 147 for the actual fix, then we pick your cleanup for libc in plus - that one clearly makes sense too. I'll investigate a bit more after why yours would crash here

**Comment by bigon** [comment]
OK, but note that the ctypes documentation is using `[]` instead of adding a coma (`,`) like you did in #147 not sure if that matters

https://docs.python.org/3/library/ctypes.html

**Comment by bigon** [comment]
https://docs.python.org/3/library/ctypes.html#ctypes._FuncPtr.argtypes:

> When a foreign function is called, each actual argument is passed to the from_param() class method of the items in the argtypes tuple, this method allows adapting the actual argument to an object that the foreign function accepts. For example, a c_char_p item in the argtypes tuple will convert a string passed as argument into a bytes object using ctypes conversion rules.

**Comment by DimStar77** [comment]
> OK, but note that the ctypes documentation is using `[]` instead of adding a coma (`,`) like you did in #147 not sure if that matters
> 
> https://docs.python.org/3/library/ctypes.html

indeed; locally I also used `[]` - it's definitively more readable and less error-prone than implying a list by a trailing comma;

147 updates

**Pull request closed without merging**
