### PR TITLE
Install libpxbackend into pkglibdir

### PR DESCRIPTION
**Pull request by amigadave**
Fixes: https://github.com/libproxy/libproxy/issues/222

### CODE REVIEW

**Comment by AdamWill** [comment]
This [broke a lot of stuff](https://bugzilla.redhat.com/show_bug.cgi?id=2209173). At least sddm and Firefox.

**Comment by janbrummer** [comment]
Hi @AdamWill It's been a long time since Fedlet :) Please create a new ticket and i'll try to fix it asap after checking back with @mcatanzaro

**Comment by AdamWill** [comment]
Oh man, hi! You're right, it has been a while =) I'll create a ticket in the morning if it's not taken care of by then, going to bed now.

**Comment by mcatanzaro** [comment]
Should be fixed by https://github.com/libproxy/libproxy/pull/231

**Pull request merged**
