### PR TITLE
config_kde improvements

### PR DESCRIPTION
**Pull request by Vogtinator**
After finding out whether to use kreadconfig5 or kreadconfig,
it uses either qtpaths or kde4-config to determine the location
of the kioslaverc config file, to be able to notice modifications
that require a cache flush.

It's not the cleanest implementation due to kde4 support, but it should improve performance significantly to solve #16.

This also fixes several errors reported by cppcheck. (Not tested, but harmless)

### CODE REVIEW

**Comment by Vogtinator** [comment]
I just noticed that this way won't invalidate if the system-wide config is being used (no user config created yet). I'll fix that tomorrow.

**Comment by Vogtinator** [comment]
Done.

**Comment by DimStar77** [comment]
@Vogtinator 'done' refers to you having corrected the statement about invalidating in case of system-config being used?

Did you push your changes? your latest commit change / push is much older than your 'done' statement

**Comment by Vogtinator** [comment]
Yup, it invalidates the cache correctly now. I tested with firefox and it printed "Flushed" whenever I touched my local or the system-wide config.
The date is the result of git rebase and commit --amend, which I prefer to commit noise.

**Comment by Vogtinator** [comment]
BTW: Would it be possible to enable C++11 (or C++14 even) support?

**Comment by Vogtinator** [comment]
dlichtenberger confirmed that it works in issue #16, so it seems to work fine.

**Pull request merged**
