### PR TITLE
python: Convert URLs to/from UTF-8 under Python 3

### PR DESCRIPTION
**Pull request by smcv**
In Python 3, strings are Unicode (UTF-16 or UTF-32 depending on build
options), and are passed to ctypes function wrappers as such.
Convert the input URL to a bytestring for processing by libproxy, and
convert the results back into (Unicode) strings by decoding them.

From the pacrunner_webkit module, it appears that libproxy expects
strings to be in UTF-8 (like GLib/GTK), so use that encoding for
bytestrings.

---

I'm not sure this is the right solution to #65, but it's certainly an improvement.

### CODE REVIEW

**Comment by smcv** [comment]
This seems to do the right thing for both ASCII and Unicode input URLs, and for both ASCII and Unicode proxies:

```
$ unset DESKTOP_SESSION
$ unset GNOME_DESKTOP_SESSION_ID
$ cat resolve-proxy.py
#!/usr/bin/python3

import libproxy
import sys

if __name__ == '__main__':
    factory = libproxy.ProxyFactory()

    for url in sys.argv[1:]:
        print(' '.join(factory.getProxies(url)))
$ PYTHONPATH=bindings/python python2 ./resolve-proxy.py http://github.com
direct://
$ PYTHONPATH=bindings/python python3 ./resolve-proxy.py http://github.com
direct://
$ PYTHONPATH=bindings/python http_proxy=http://🖧.🤷 python2 ./resolve-proxy.py
http://🖥.🗺
$ PYTHONPATH=bindings/python http_proxy=http://🖧.🤷 python3 ./resolve-proxy.py
http://🖥.🗺
```

**Comment by DimStar77** [comment]
@npmccallum Can you please give your 2 cents here? From what I have in mind, this looks correct; also the IRI handling should be proper

**Comment by npmccallum** [comment]
LGTM

**Comment by smcv** [comment]
> also the IRI handling should be proper

To confirm: this code change assumes that the URL argument of `px_proxy_factory_get_proxies()` is allowed to be a UTF-8-encoded IRI (for example it might be `u'http://кц.рф/пример'.encode('utf-8')`, which is `b'http://\xd0\xba\xd1\x86.\xd1\x80\xd1\x84/\xd0\xbf\xd1\x80\xd0\xb8\xd0\xbc\xd0\xb5\xd1\x80'`).

It also assumes that if `px_proxy_factory_get_proxies()` returns non-ASCII strings, then they are IRIs encoded in UTF-8.

Are both of those assumptions correct?

**Pull request merged**
