### PR TITLE
Update build to mozjs38

### PR DESCRIPTION
**Pull request by jlinton**
This pulls libproxy forward a little, and brings it in line with
gnome which is also on mozjs24.

This hasn't been tested much beyond starting a couple of dependent processes (aka I don't have a lot of proxy configurations I can test). 

Thanks

Signed-off-by: Jeremy Linton jeremy.linton@arm.com

### CODE REVIEW

**Comment by jlinton** [comment]
Hmm I sort of expected the CI to fail the building process because the dependencies changed. I didn't expect it to fail `make test`. Although it failed the "allowed to fail" ones on osx, do those normally fail?

**Comment by DimStar77** [comment]
the last three commits at least should be squashed into one

as for the CI: that is a large WIP piece - close to no plugins are being built yet (certainly something to improve upon)

**Comment by amigadave** [comment]
Commit 2b3216a to fix the get-pac-test failures is incorrect, and I posted an improved fix in https://github.com/libproxy/libproxy/pull/48 (although I did not text on OSX or BSD).

**Comment by bigon** [comment]
Any progress on this?

**Comment by Keruspe** [comment]
@jlinton any news on updating wrt @DimStar77 comments?

**Comment by jlinton** [comment]
I was thrashing about with the osx fix, but I fail to see how simply removing the close solves anything. shutdown() by itself simply blocks the TCP connection it doesn't cleanup the socket/fd.

Anyway, I will revisit this in the context of mozjs38 in the next few days.

**Comment by jlinton** [comment]
Ok, github fun, since these were all on the same branch you get them together<shrug>

Anyway, I updated it to work with mozjs38

**Pull request merged**
